spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: admin
  password: admin

camunda:
  bpm:
    history-time-to-live: 180 # History Time to Live set to 180 days (global setting)
